"""edit column user

Revision ID: 1126357bce1b
Revises: 220866f7b69e
Create Date: 2025-12-24 21:31:45.898038

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '1126357bce1b'
down_revision: Union[str, Sequence[str], None] = '220866f7b69e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'email_verified_at',
               existing_type=mysql.DATETIME(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'email_verified_at',
               existing_type=mysql.DATETIME(),
               nullable=False)
    # ### end Alembic commands ###
