"""fix column user

Revision ID: 16ee954ce1a6
Revises: b9499a924b3c
Create Date: 2025-12-24 21:25:40.150019

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '16ee954ce1a6'
down_revision: Union[str, Sequence[str], None] = 'b9499a924b3c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('uq_user_event'), table_name='registrations')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('uq_user_event'), 'registrations', ['user_id', 'event_id'], unique=True)
    # ### end Alembic commands ###
