"""create model user

Revision ID: 220866f7b69e
Revises: 850821753cd3
Create Date: 2025-12-24 21:29:48.084066

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '220866f7b69e'
down_revision: Union[str, Sequence[str], None] = '850821753cd3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('username', mysql.VARCHAR(length=120), nullable=False),
    sa.Column('email', mysql.VARCHAR(length=190), nullable=False),
    sa.Column('phone', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('password_hash', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('platform_role', mysql.ENUM('PLATFORM_ADMIN', 'USER'), nullable=False),
    sa.Column('email_verified_at', mysql.DATETIME(), nullable=False),
    sa.Column('status', mysql.ENUM('ACTIVE', 'SUSPENDED', 'BANNED'), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
