"""fix column user again

Revision ID: 850821753cd3
Revises: 16ee954ce1a6
Create Date: 2025-12-24 21:27:03.630345

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '850821753cd3'
down_revision: Union[str, Sequence[str], None] = '16ee954ce1a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('uq_user_event'), table_name='registrations')
    op.drop_table('registrations')
    op.drop_index(op.f('role'), table_name='roles')
    op.drop_table('roles')
    op.drop_index(op.f('registration_id'), table_name='payments')
    op.drop_table('payments')
    op.drop_table('events')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('id_organizer', mysql.BIGINT(unsigned=True), autoincrement=False, nullable=False),
    sa.Column('judul_event', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('deskripsi', mysql.TEXT(), nullable=False),
    sa.Column('lokasi', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('jam_mulai', mysql.TIME(), nullable=False),
    sa.Column('jam_selesai', mysql.TIME(), nullable=False),
    sa.Column('harga', mysql.DECIMAL(precision=12, scale=2), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['id_organizer'], ['users.id'], name='events_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('payments',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('registration_id', mysql.BIGINT(unsigned=True), autoincrement=False, nullable=False),
    sa.Column('provider', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('amount', mysql.DECIMAL(precision=12, scale=2), nullable=False),
    sa.Column('status_payment', mysql.VARCHAR(length=60), nullable=False),
    sa.Column('payment_ref', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['registration_id'], ['registrations.id'], name=op.f('payments_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('registration_id'), 'payments', ['registration_id'], unique=True)
    op.create_table('roles',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('role', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('role'), 'roles', ['role'], unique=True)
    op.create_table('registrations',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('event_id', mysql.BIGINT(unsigned=True), autoincrement=False, nullable=False),
    sa.Column('user_id', mysql.BIGINT(unsigned=True), autoincrement=False, nullable=False),
    sa.Column('status', mysql.ENUM('pending', 'paid', 'cancelled'), nullable=False),
    sa.Column('qr_token', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('is_attended', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], name=op.f('registrations_ibfk_1')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('registrations_ibfk_2')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('uq_user_event'), 'registrations', ['user_id', 'event_id'], unique=True)
    # ### end Alembic commands ###
