"""add new table

Revision ID: ad77fae0eb7c
Revises: 9273d6c88734
Create Date: 2025-12-16 22:27:20.741087

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'ad77fae0eb7c'
down_revision: Union[str, Sequence[str], None] = '9273d6c88734'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events',
    sa.Column('id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('id_organizer', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('judul_event', sa.String(length=255), nullable=False),
    sa.Column('deskripsi', mysql.TEXT(), nullable=False),
    sa.Column('lokasi', sa.String(length=255), nullable=False),
    sa.Column('jam_mulai', sa.Time(), nullable=False),
    sa.Column('jam_selesai', sa.Time(), nullable=False),
    sa.Column('harga', mysql.DECIMAL(precision=12, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['id_organizer'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('registrations',
    sa.Column('id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('event_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('user_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('status', mysql.ENUM('pending', 'paid', 'cancelled'), nullable=False),
    sa.Column('qr_token', sa.String(length=255), nullable=True),
    sa.Column('is_attended', sa.BOOLEAN(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'event_id', name='uq_user_event')
    )
    op.create_table('payments',
    sa.Column('id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('registration_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('amount', sa.DECIMAL(precision=12, scale=2), nullable=False),
    sa.Column('status_payment', sa.String(length=60), nullable=False),
    sa.Column('payment_ref', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['registration_id'], ['registrations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('registration_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('payments')
    op.drop_table('registrations')
    op.drop_table('events')
    # ### end Alembic commands ###
