"""feat: modify user table

Revision ID: d9c7c0a89f88
Revises: a0d0b1d42a72
Create Date: 2026-01-27 21:02:30.195123

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'd9c7c0a89f88'
down_revision: Union[str, Sequence[str], None] = 'a0d0b1d42a72'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizers',
    sa.Column('id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('name', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('slug', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('status', mysql.ENUM('PENDING', 'VERIFIED', 'SUSPENDED'), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('users',
    sa.Column('id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('google_id', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('email', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('full_name', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('avatar', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('role', mysql.ENUM('PLATFORM_ADMIN', 'USER'), nullable=False),
    sa.Column('phone_number', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('user_status', mysql.ENUM('ACTIVE', 'SUSPENDED', 'BANNED'), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_google_id'), 'users', ['google_id'], unique=True)
    op.create_table('events',
    sa.Column('id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('organizer_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('created_by', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('title', mysql.VARCHAR(length=160), nullable=False),
    sa.Column('slug', mysql.VARCHAR(length=120), nullable=False),
    sa.Column('description', mysql.TEXT(), nullable=True),
    sa.Column('venue_name', mysql.VARCHAR(length=160), nullable=True),
    sa.Column('venue_address', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('start_at', mysql.DATETIME(), nullable=False),
    sa.Column('end_at', mysql.DATETIME(), nullable=False),
    sa.Column('visibility', mysql.ENUM('DRAFT', 'SUBMITTED', 'APPROVED', 'PUBLISHED', 'REJECTED', 'ENDED'), nullable=False),
    sa.Column('is_free', sa.BOOLEAN(), nullable=False),
    sa.Column('currency', mysql.CHAR(length=3), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['organizer_id'], ['organizers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('organizer_members',
    sa.Column('organizer_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('user_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('role', mysql.ENUM('ORGANIZER_ADMIN', 'FINANCE', 'GATE', 'VIEWER'), nullable=False),
    sa.Column('status', mysql.ENUM('ACTIVE', 'INACTIVE'), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['organizer_id'], ['organizers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('organizer_id', 'user_id')
    )
    op.create_table('payouts',
    sa.Column('id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('organizer_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('period_start', mysql.DATETIME(), nullable=False),
    sa.Column('period_end', mysql.DATETIME(), nullable=False),
    sa.Column('gross_amount', mysql.DECIMAL(precision=15, scale=2), nullable=False),
    sa.Column('fee_amount', mysql.DECIMAL(precision=15, scale=2), nullable=False),
    sa.Column('net_amount', mysql.DECIMAL(precision=15, scale=2), nullable=False),
    sa.Column('status', mysql.ENUM('PENDING', 'PROCESSING', 'PAID', 'FAILED'), nullable=False),
    sa.Column('paid_at', mysql.DATETIME(), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['organizer_id'], ['organizers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('profiles',
    sa.Column('id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('full_name', mysql.VARCHAR(length=120), nullable=True),
    sa.Column('phone', mysql.VARCHAR(length=30), nullable=True),
    sa.Column('gender', mysql.ENUM('MALE', 'FEMALE', 'OTHER'), nullable=True),
    sa.Column('birth_date', sa.DATE(), nullable=True),
    sa.Column('avatar_url', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('event_approvals',
    sa.Column('id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('event_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('submitted_by', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('decided_by', mysql.BIGINT(unsigned=True), nullable=True),
    sa.Column('status', mysql.ENUM('SUBMITTED', 'APPROVED', 'REJECTED'), nullable=False),
    sa.Column('notes', mysql.VARCHAR(length=500), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['decided_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.ForeignKeyConstraint(['submitted_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('orders',
    sa.Column('id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('event_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('organizer_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('buyer_user_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('order_code', mysql.VARCHAR(length=40), nullable=False),
    sa.Column('status', mysql.ENUM('PENDING', 'PAID', 'EXPIRED', 'CANCELED', 'REFUNDED'), nullable=False),
    sa.Column('currency', mysql.CHAR(length=3), nullable=False),
    sa.Column('subtotal', mysql.DECIMAL(precision=15, scale=2), nullable=False),
    sa.Column('discount_total', mysql.DECIMAL(precision=15, scale=2), nullable=False),
    sa.Column('fee_total', mysql.DECIMAL(precision=15, scale=2), nullable=False),
    sa.Column('grand_total', mysql.DECIMAL(precision=15, scale=2), nullable=False),
    sa.Column('expires_at', mysql.DATETIME(), nullable=True),
    sa.Column('paid_at', mysql.DATETIME(), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['buyer_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.ForeignKeyConstraint(['organizer_id'], ['organizers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_code')
    )
    op.create_table('promo_codes',
    sa.Column('id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('organizer_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('event_id', mysql.BIGINT(unsigned=True), nullable=True),
    sa.Column('code', mysql.VARCHAR(length=40), nullable=False),
    sa.Column('type', mysql.ENUM('PERCENT', 'AMOUNT'), nullable=False),
    sa.Column('value', mysql.DECIMAL(precision=15, scale=2), nullable=False),
    sa.Column('quota', mysql.INTEGER(), nullable=True),
    sa.Column('used_count', mysql.INTEGER(), nullable=False),
    sa.Column('valid_from', mysql.DATETIME(), nullable=False),
    sa.Column('valid_until', mysql.DATETIME(), nullable=False),
    sa.Column('status', mysql.ENUM('ACTIVE', 'INACTIVE'), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.ForeignKeyConstraint(['organizer_id'], ['organizers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('ticket_types',
    sa.Column('id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('event_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('name', mysql.VARCHAR(length=120), nullable=False),
    sa.Column('price', mysql.DECIMAL(precision=15, scale=2), nullable=False),
    sa.Column('quota', mysql.INTEGER(), nullable=False),
    sa.Column('sold_count', mysql.INTEGER(), nullable=False),
    sa.Column('sale_start_at', mysql.DATETIME(), nullable=False),
    sa.Column('sale_end_at', mysql.DATETIME(), nullable=False),
    sa.Column('max_per_order', mysql.INTEGER(), nullable=False),
    sa.Column('status', mysql.ENUM('ACTIVE', 'INACTIVE'), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('order_items',
    sa.Column('id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('order_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('ticket_type_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('qty', mysql.INTEGER(), nullable=False),
    sa.Column('unit_price', mysql.DECIMAL(precision=15, scale=2), nullable=False),
    sa.Column('subtotal', mysql.DECIMAL(precision=15, scale=2), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['ticket_type_id'], ['ticket_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payments',
    sa.Column('id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('order_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('provider', mysql.VARCHAR(length=60), nullable=False),
    sa.Column('method', mysql.VARCHAR(length=60), nullable=False),
    sa.Column('amount', mysql.DECIMAL(precision=15, scale=2), nullable=False),
    sa.Column('status', mysql.ENUM('INITIATED', 'PENDING', 'PAID', 'FAILED', 'EXPIRED', 'REFUNDED'), nullable=False),
    sa.Column('payment_ref', mysql.VARCHAR(length=191), nullable=True),
    sa.Column('paid_at', mysql.DATETIME(), nullable=True),
    sa.Column('provider_payload', mysql.JSON(), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payout_lines',
    sa.Column('id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('payout_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('order_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('amount', mysql.DECIMAL(precision=15, scale=2), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['payout_id'], ['payouts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tickets',
    sa.Column('id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('order_item_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('ticket_code', mysql.VARCHAR(length=80), nullable=False),
    sa.Column('qr_token', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('attendee_name', mysql.VARCHAR(length=120), nullable=True),
    sa.Column('attendee_email', mysql.VARCHAR(length=191), nullable=True),
    sa.Column('status', mysql.ENUM('ISSUED', 'CHECKED_IN', 'VOID', 'REFUNDED'), nullable=False),
    sa.Column('issued_at', mysql.DATETIME(), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['order_item_id'], ['order_items.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('qr_token'),
    sa.UniqueConstraint('ticket_code')
    )
    op.create_table('checkins',
    sa.Column('id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('ticket_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('gate_user_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('scanned_at', mysql.DATETIME(), nullable=False),
    sa.Column('result', mysql.ENUM('OK', 'DUPLICATE', 'INVALID', 'BLOCKED'), nullable=False),
    sa.Column('device_id', mysql.VARCHAR(length=80), nullable=True),
    sa.Column('meta', mysql.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['gate_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('checkins')
    op.drop_table('tickets')
    op.drop_table('payout_lines')
    op.drop_table('payments')
    op.drop_table('order_items')
    op.drop_table('ticket_types')
    op.drop_table('promo_codes')
    op.drop_table('orders')
    op.drop_table('event_approvals')
    op.drop_table('profiles')
    op.drop_table('payouts')
    op.drop_table('organizer_members')
    op.drop_table('events')
    op.drop_index(op.f('ix_users_google_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('organizers')
    # ### end Alembic commands ###
